webpage/webpage/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from web_app import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from web_app.sitemaps import StaticViewSitemap,SnippetSitemap,CollegeSitemap

sitemaps = {
    # 'static': StaticViewSitemap,
    'snippet':SnippetSitemap,
    'college':CollegeSitemap,

}


urlpatterns = [

    url(r'^insert$', views.insert, name="insert"),
    
    path('main_course/<slug>',views.course_detail,name="course_detail"),

    path('course/<slug>',views.course_slug,name='course_slug'),
    
    path('admin/', admin.site.urls),
    
    url(r'^$',views.index,name="index"),
    
    path('register/',views.registration_page,name="registartion_page"),
    
    path('login/',views.user_login,name="Login_page"),
    
    path('logout/',views.user_logout,name="logout"),
    
    path('profile/',views.profile_page,name="profile_page"),
    
    path("update_profile/", views.edit_student_form, name ="student_edit_form"),
    
    path('Degree/',views.degree_details,name="degree_detail"),
    
    path('Branch/',views.branch_detail,name="branch"),
    
    path('Exam/',views.Exam_details,name="exam"),

    path('ajax/validate/',views.check,name="check"),
    
    url(r'^ajax_calls/search/',views.autocompleteModel,name="auto_degree"),
    
    url(r'^ajax_calls/searchs/',views.autocomplte_branch,name="auto_branch"),
    
    url(r'^ajax_calls/search-course/',views.autocomplte_course,name="auto_course"),
    
    url(r'^course_profile/',views.List_view.as_view(),name="listview"),
    
    url(r'^manage_course/',views.managecourse,name="manage_course"),
    
    path("manage/college/courses/<pk>",views.managecourse,name="manage_course"),
    
    path('college/coures/<name>/<pk>/add',views.dynamicfield,name="dynamic-arg"),
    
    path("courses/<int:pk>", views.edit_course_form, name ="course_edit_form"),

    url(r'^course',views.dynamicfield,name="dynamic"),

    path('manage/',views.manage,name="manage"),

    path('manage-college/',views.manage_college,name="college"),

    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps},name='d'),

    path('about',views.about,name="about"),

    path('add-college/',views.add_college,name="add-college"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webpage/web_app/models.py
from django.db import models
from django.contrib.auth.models import User
from multiselectfield import MultiSelectField
import datetime
from django.template.defaultfilters import slugify
from django.urls import reverse



#-----------------------------------Student Detail------------------------------------------------------------------


streams = ( ('Engineering','Engineering'),('Medical','Medical'),('Law','Law'),('Arts','Arts'))
exams = ( ('JEE Main','JEE Main'),('JEE Advance','JEE Advance'),('VITEEE','VITEEE'),('GATE','GATE'))

class Student_profile(models.Model):

    user=models.OneToOneField(User,on_delete=models.CASCADE)

    PhoneNumber = models.CharField(max_length=250,default="")

    qualification = models.CharField(max_length=250,default="")

    subjects = models.CharField(max_length=250,default="")

    percentage = models.CharField(max_length=250,default="")

    Description = models.CharField(max_length=250,default="")

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)


    def __str__(self):
        return self.user.username
    #def get_absolute_url(self):
    #    return reverse('profile-update', kwargs={'pk': self.pk})

#--------------------------------------Hobby Detail---------------------------------------------------------------

class Hobby_details(models.Model):

    types = (('None','Please Select'), ('Music','Music'), ('Sports','Sports'))

    student = models.ForeignKey('Student_profile', on_delete=models.CASCADE,null=True,blank=True,related_name = "hob")

    hobby = models.CharField(max_length=256)

    hobby_choices = models.CharField(max_length=25,choices = types, default='None')

    hobby_name = models.CharField(max_length=245)


#-------------------------------------------Degree_detail--------------------------------------------------------

class Degree_detail(models.Model):

    global streams

    name = models.CharField(max_length=250)

    stream = models.CharField(max_length=258,choices = streams ,default='Engineering')

    publish = models.BooleanField(default = True)

    def __str__(self):

        return self.name

#------------------------------------------Branch_detail-----------------------------------------------------------

class Branch_detail(models.Model):

    global streams

    name = models.CharField(max_length=250)

    stream = models.CharField(max_length=258,choices = streams ,default='Engineering')

    publish = models.BooleanField(default = True)

    def __str__(self):

        return self.name

#--------------------------------------Exam_detail---------------------------------------------------------------


class Exam_detail(models.Model):

    global exams

    name = models.CharField(max_length=250)

    Exam = models.CharField(max_length=258,choices = exams,default='GATE')

    publish = models.BooleanField(default = True)

    def __str__(self):

        return self.Exam


#----------------------------------------Course_page-------------------------------------------------------------

class Course_page(models.Model):

    college = models.ForeignKey('College_detail',on_delete=models.CASCADE,null=True,blank=True)
    
    global exams

    course_name = models.CharField(max_length=256)

    degree = models.CharField(max_length=50)

    branch = models.CharField(max_length=50)

    exam = models.ManyToManyField(Exam_detail,blank=True,default=None)

    course_duration = models.IntegerField()

    eligibility = models.CharField(max_length=223)

    course_detail = models.CharField(max_length=256)

    publish = models.BooleanField(default = True)

    created_date =  models.DateField(("Date"), default=datetime.date.today)

    updated_date = models.DateField(("Date"), default=datetime.date.today)

    slug = models.SlugField(blank=True)


    def save(self, *args, **kwargs):

        l = ['of','is','an','the','was'] 

        k = self.course_name.split(' ')

        mk = k.copy()

        for i in k:

            if i in l:

                mk.remove(i)

        new = "-".join(str(x) for x in mk)
       
        new_source = new+ "-careers360"
        
        self.slug = slugify(new_source)

        super(Course_page, self).save(*args, **kwargs)

    def get_absolute_url(self):

        return "hello"

#------------------------------------------course_page foreignkey -------------------------------------------------

class subcoursepage(models.Model):

    subcourse = models.ForeignKey('Course_page', on_delete=models.CASCADE,null=True,blank=True,related_name = "hob")

    category = models.CharField(max_length=254)

    Total_fees = models.IntegerField()

#----------------------------------------streams--------------------------------------------------------------------------

class Streams(models.Model):

    streambranch = models.CharField(max_length = 222)

    streamdegree =  models.CharField(max_length = 122)

    Stream = models.CharField(max_length = 122)

#-----------------------------------College Detail---------------------------------------------------

class College_detail(models.Model):

    college_name = models.CharField(max_length=122)

    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs):

        l = ['of','is','an','the','was'] 

        k = self.college_name.split(' ')

        mk = k.copy()

        for i in k:

            if i in l:

                mk.remove(i)

        new = "-".join(str(x) for x in mk)
        
        self.slug = slugify(new)

        super(College_detail, self).save(*args, **kwargs)

    def get_absolute_url(self):

     
        return "hello"

webpage/web_app/forms.py
from django import forms
from django.contrib.auth.models import User
from web_app.models import Student_profile,Hobby_details,Course_page,Degree_detail,Branch_detail,Exam_detail,subcoursepage,Streams,College_detail
from dal import autocomplete
from django.forms.models import inlineformset_factory

class SignUpForm(forms.ModelForm):

    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():

        model = User

        fields = ('username', 'email', 'password')

class Register(forms.ModelForm):

    class Meta():

        model = Student_profile

        fields = ('PhoneNumber','qualification','subjects','percentage','Description','profile_pic')

class Hobbies(forms.ModelForm):

    types = (('None','Please Select'), ('Music','Music'), ('Sports','Sports'))

    hobby_choices = forms.ChoiceField(choices=types)

    class Meta():

        model = Hobby_details

        fields = ('hobby','hobby_choices','hobby_name')

    def clean_hobby_choices(self):

        name=self.cleaned_data.get('hobby_choices')

        print(name)

        if name == "None":

            print("kjsdbkjsdbk")

            raise forms.ValidationError("You must select the value")

        else:

            return name

    def clean_hobby_name(self):

        print("hello name")



#---------------------------------------------CourseForm-----------------------------------------------------
class CourseForm(forms.ModelForm):

    course = Course_page.objects.all()

    exam = forms.ModelMultipleChoiceField( required=True, queryset=Exam_detail.objects.all())

    course_detail = forms.CharField(widget=forms.Textarea)

    class Meta():

        model = Course_page

        fields = ('course_name','course_duration','degree','branch','exam','eligibility','course_detail','publish')

    def clean_course_name(self):

        name = self.cleaned_data.get('course_name')

        m = Course_page.objects.all().values_list('course_name', flat=True)

        l = []

        for i in m:

            l.append(i)

        if name in l:

            raise forms.ValidationError("This course already taken")

        else:

            return name

class Degree_detailForm(forms.ModelForm):

    class Meta():
        
        model = Degree_detail

        fields = ('name','stream','publish')

class Branch_detailForm(forms.ModelForm):


    class Meta():

        model = Branch_detail

        fields = ('name','stream','publish')

class Exam_detailForm(forms.ModelForm):

    class Meta():

        model = Exam_detail

        fields = ('name','Exam','publish')

class subcourseform(forms.ModelForm):

    class Meta():

        model = subcoursepage

        fields = ('category','Total_fees')

class streamform(forms.ModelForm):

    class Meta():

        model = Streams

        fields = ('streambranch','streamdegree','Stream')

class collegeForm(forms.ModelForm):

    class Meta():

        model = College_detail

        fields = ('college_name',)

webpage/templates/add_college.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="utf-8">
	<title>Add college</title>

	<style>
	.container{
		font-size: 23px;
	}

	</style>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
<body>
 <div class="container">
<form method="post">
<h1>Add College</h1>

{% csrf_token %}
<br>
<label>College Name</label> {{college_add.college_name}}

<input type="submit" value ="Add">
</form>

</body>
</html>

webpage/templates/basic.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="utf-8">
	<title>First Website</title>

	<style>
	.container{
		font-size: 23px;
	}

	</style>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
<body>

  <div class="container">
		<nav class="navbar navbar-inverse">
 <div class="container-fluid">
	 <ul class="nav navbar-nav">
		 <li class="active"><a href="{% url 'index' %}">Home</a></li>
     {% if user.is_authenticated %}
		 	<li><a href="{% url 'profile_page' %}">Profile</a></li>
			<li><a href="{% url 'student_edit_form'  %}">Edit profile </a></li>
      <li><a href="{% url 'logout' %}">Logout</a></li>
     {% else %}
     <li><a href="{% url 'registartion_page' %}">Register</a></li>
      <li><a class="navbar-link" href="{% url 'Login_page' %}">Login</a></li>
     {% endif %}
	 </ul>
 </div>
</nav>
{% block body_block %}
    {# Anything outside of this will be inherited if you use extend.#}
    {% endblock %}
  </div>
</body>
</html>

webpage/templates/course_detail.html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


<link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" /> <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"> </script> <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>

<link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" /> <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"> </script> <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>

<style>
h2
{
padding-left: 250px;
font-size: 42px;
text-transform: uppercase;
}
h3{
text-transform: uppercase;
font-weight: lighter;
}

</style>

<script>
$(document).ready(function(){
        $("#hi").fadeOut("fast")
    $(".btn-info").click(function(){
        var b = '{{course.course_name.errors}}'
        var a=document.getElementById("id_course_name").value;
        console.log(b)
        $("#hi").fadeIn();
    });
});

</script>

</head>
<body>

{% block body_block %}
<div class="jumbotron">
<div class="container">

<form method ="post" id ="framework_form">
  {% csrf_token %}
<h2>Course Details Form </h2>
<div id="preid">
<pre>

<label >COURSE NAME</label>      {{course.course_name}}
        <font color="red">      {{course.course_name.errors}}</font>
<label>COURSE DURATION</label>  {{course.course_duration}}

<label>Degree</label>           {{course.degree}}

<label>Branch</label>           {{course.branch}}

<label>Exam</label>             {{course.exam}}

<label>ELIGIBILITY</label>      {{course.eligibility}}

<label>COURSE DETAIL</label>    {{course.course_detail}}

<label>CATEGORY</label>         {{course.category}}

<label>TOTAL FEES</label>       {{course.Total_fees}}


    <input type="submit" class="btn btn-primary">

</pre>
</div>

</form>
</div>
</div>

<script>

        $(document).ready(function(){
            $("#id_degree").autocomplete({
                source: "/ajax_calls/search/",
                minLength: 2,

                open: function(){
                    setTimeout(function () {
                        $('.ui-autocomplete').css('z-index', 99);
                    }, 0);
                }
              });
        });

        $(document).ready(function(){
            $("#id_branch").autocomplete({
                source: "/ajax_calls/searchs/",
                minLength: 2,

                open: function(){
                    setTimeout(function () {
                        $('.ui-autocomplete').css('z-index', 99);
                    }, 0);
                }
              });
        });





</script>

   <link href="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/css/bootstrap.min.css"
        rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <link href="http://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/css/bootstrap-multiselect.css"
        rel="stylesheet" type="text/css" />
    <script src="http://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/js/bootstrap-multiselect.js"
        type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
            $('#id_exam').multiselect({
                includeSelectAllOption: true

            });

        });
    </script>

{% endblock %}
</body>
</html>

webpage/templates/course_formset.html
<html>

<head>
{% load staticfiles %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


<link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" /> <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"> </script> <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>

<link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" /> <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"> </script> <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>



<style type="text/css">
    
#a1
 { 
  
  width: 150px;
  
  height:50px;
 
 }

#d{

    color: green;

    font-size: 20px;
}

#b{

color: blue;

font-size: 20px;

}
</style>
</head>

<body>
<div class="jumbotron">
<div class="container">
   
<h1>Course Page</h1><br>    
 <div class="col-md-6">
        <form action="" method="post" id ="contact">
           
            {% csrf_token %}


            {{ course.as_p }}

 <div id="d"></div>

 <div id = "b"></div>  

            <table class="table">

               {{ formset.management_form }}
                {% for form in formset %}

                {% if forloop.first %}

                        <thead>

                        <tr>

                            {% for field in form.visible_fields %}

                            <th>{{ field.label|capfirst }}</th>
                        
                            {% endfor %}

                        </tr>

                        </thead>


                {% endif %}

                    <tr class="{% cycle row1 row2 %} formset_row">

                        {% for field in form.visible_fields %}

                        <td>


                                {# Include the hidden fields in the form #}
                                {% if forloop.first %}

                                    {% for hidden in form.hidden_fields %}

                                    {{ hidden }}


                                    {% endfor %}

                                {% endif %}

                                {% if form.field.errors.as_ul %}

                                {% endif %}

                            {{ field }}

                        </td>

                    {% endfor %}

                    </tr>

                {% endfor %}


            </table>


                <input type="submit" class="btn btn-block btn-primary" id ="a1">
        </form>
    </div>
</div>
</div>


<!-- Modal when adding comment for upload -->

<form method="post" id="publsihform">
  {% csrf_token %}
  <div class="modal fade" id="fileUploadModal" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Add Comment</h4>
        </div>
        <div class="modal-body">
          <p><textarea id = "commentsUpload"class="form-control custom-control" rows="3" style="resize:none"></textarea></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" id='publishbutton' data-dismiss="modal">Submit</button>
        </div>
      </div>
    </div>
  </div>
</form>



<script>
  $( function() {
    $( "#id_created_date").datepicker();
  } );
  </script>
    <script src="{% static 'formset/jquery.formset.js' %}"></script>
    <script type="text/javascript">
        $('.formset_row').formset({
            addText: 'add more',
            deleteText: 'remove',
            prefix: 'form',
        });

    </script>

<script>
        
    $(document).ready(function(){
        var degree_stream;
        var branch_stream;
            $("#id_degree").autocomplete({
                source: function( request, response ) {
                   jQuery.get("/ajax_calls/search/", {
           'term': request.term
       }, function (data) {
        console.log(data)       
        var m = data[0];    
        txt= m["stream"] ;
        degree_stream = txt;
        response(data);
       });
               },
                minLength: 2,
                open: function(){3
                    setTimeout(function () {
                    $('.ui-autocomplete').css('z-index', 99);
                    }, 0);
                },
              });  
       
            $("#id_branch").autocomplete({
                source: function( request, response ) {
                   jQuery.get("/ajax_calls/searchs/", {
           'term': request.term
       }, function (data) {

        var m = data[0];    
        txt= m["stream"];
        branch_stream=txt;

        console.log("degree name ",degree_stream)
        console.log("branch name",branch_stream)
        if(degree_stream==branch_stream)
        {
        document.getElementById("b").innerHTML = "<li>"+txt+"</li>";
        document.getElementById("d").innerHTML = "";
       }
       
       else

       {

         document.getElementById("d").innerHTML = "<li>"+degree_stream+"</li>";
          document.getElementById("b").innerHTML = "<li>"+branch_stream+"</li>";
       }

       response(data);

       });
               },
                minLength: 2,
                open: function(){
                    setTimeout(function () {
                    $('.ui-autocomplete').css('z-index', 99);
                    }, 0);
                },
              });  
        });

</script>

    <link href="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <link href="http://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/css/bootstrap-multiselect.css" rel="stylesheet" type="text/css" />
    <script src="http://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/js/bootstrap-multiselect.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
            $('#id_exam').multiselect({
                includeSelectAllOption: true

            });

        });

    </script>

<script>

$( document ).ready(function() {

   $( "#id_publish" ).change(function() {

            var val = $(this).is(':checked');

            if(val==false)
                
                {

                  var h = $('#fileUploadModal').modal('show')
      
                  $('#publishbutton').on('click', function() {

                        $.ajax({ 

                         type: "POST",
                         url : "/insert",
                         data:
                         {

                          val : $('#commentsUpload').val(),
                          csrfmiddlewaretoken: $('#publsihform input[name=csrfmiddlewaretoken]').val(),
                         },
                         success: function(response) {

                          console.log("success")

                            }
                    })

                    });
            }      
  });

    });

</script>
</body>
</html>

webpage/templates/course_update.html
<!DOCTYPE html>
<html>
<head>
  <style>
  form{
  width: 950px;
  padding: 20px;
  border: 1px solid #270644;

  }


#b{

color: blue;

font-size: 20px;
}

#d{

    color: green;

    font-size: 20px;
    text-align:left;
}

  </style>
	<title></title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


<link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" /> <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"> </script> <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>

<link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" /> <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"> </script> <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>


</head>
<body>
<div class="container">
<form method="post" action="">
  <h3>update course </h3>
{{ form.as_p }}
 <div id="d"></div>

 <div id = "b"></div>  
{% csrf_token %}
<br>
<input type="submit" class="btn btn-primary" value="Update">
</form>
</div>


<script>
        
    $(document).ready(function(){
        var degree_stream;
        var branch_stream;


            $("#id_degree").autocomplete({
                source: function( request, response ) {
                   jQuery.get("/ajax_calls/search/", {
           'term': request.term
       }, function (data) {
        console.log("This is ",data)       
        var m = data[0];    
        txt= m["stream"] ;
        degree_stream = txt;
        response(data);
       });
               },
                minLength: 2,
                open: function(){
                    setTimeout(function () {
                    $('.ui-autocomplete').css('z-index', 99);
                    }, 0);
                },
              });  
       
            $("#id_branch").autocomplete({
                source: function( request, response ) {
                   jQuery.get("/ajax_calls/searchs/", {
           'term': request.term
       }, function (data) {

        var m = data[0];    
        txt= m["stream"];
        branch_stream=txt;

        console.log("degree name ",degree_stream)
        console.log("branch name",branch_stream)
        if(degree_stream==branch_stream)
        {

        document.getElementById("b").innerHTML = "<li>"+txt+"</li>";
       
        document.getElementById("d").innerHTML = "";
       }
       
       else

       {

         document.getElementById("d").innerHTML = "<li>"+degree_stream+"</li>";
          document.getElementById("b").innerHTML = "<li>"+branch_stream+"</li>";
       }

       response(data);
       });
               },
                minLength: 2,
                open: function(){
                    setTimeout(function () {
                    $('.ui-autocomplete').css('z-index', 99);
                    }, 0);
                },
              });  
    

        var a = document.getElementById("id_degree").value;

        var b = document.getElementById("id_branch").value;

        console.log(a);

        var d = "{{degree_stream}}";

        var b = "{{branch_stream}}";

        if(d==b)
        {

          document.getElementById("b").innerHTML = "<li>"+d+"</li>";
       
        document.getElementById("d").innerHTML = "";

        }
        else{

          document.getElementById("d").innerHTML = "<li>"+d+"</li>";
          document.getElementById("b").innerHTML = "<li>"+b+"</li>";

        }

        });

</script>

    <link href="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <link href="http://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/css/bootstrap-multiselect.css" rel="stylesheet" type="text/css" />
    <script src="http://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/js/bootstrap-multiselect.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
            $('#id_exam').multiselect({
                includeSelectAllOption: true

            });

        });
    </script>


</body>
</html>